source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'jekyll'
gem 'wdm', '~> 0.1.0' if Gem.win_platform?
gem 'yui-compressor'
gem 'listen'
gem 'rouge'
gem 'nuggets'
gem 'jekyll-sitemap'
gem 'net-ssh'
gem 'net-sftp'
gem 'jekyll-autolink_email'
gem 'jekyll_version_plugin'
gem 'rubyzip', '>= 1.0.0'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'font-awesome-sass'
gem 'mini_magick'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-assets'
